### ISSUE TITLE
Clean when running bundle install?

### ISSUE THREAD

**Issue by XhmikosR** [ruby/setup-ruby#113]
Hello!

I'm experimenting to switching to the `ruby/setup-ruby` action. Everything looks good, `--no-document` is passed like I've been already doing myself.

One thing I noticed from quick look around the source code, is that `--clean` isn't being passed in bundler. I've been using this option so that the cache doesn't keep older, no longer needed gems and its size doesn't grow too fast.

Would it be possible to add an option for it (disabled by default)?

**Comment by eregon** [comment]
Do you mean using https://bundler.io/v1.5/bundle_clean.html?
I don't see a `--clean` option in https://bundler.io/v1.5/man/bundle-install.1.html

Maybe we should just no reuse the cache if the Gemfile.lock (checked in or generated from Gemfile) changes?
Trade-off is that might cause e.g. recompiling C extensions when otherwise it wouldn't be needed (if the version of those C extensions doesn't change).
OTOH GitHub caches are evicted if not accessed within the last week: https://github.com/actions/cache#cache-limits
So having to recompile C extensions every now and then is kind of expected.

Currently it indeed keeps the older gems:
https://github.com/ruby/setup-ruby/blob/21351ecc0a7c196081abca5dc55b08f085efe09a/index.js#L252-L253

I'm a bit wary of using commands/flags of Bundler that are not frequently used as they are more likely to have some bugs, and make the whole process more complicated and harder to test.

**Comment by slonopotamus** [comment]
https://bundler.io/man/bundle-install.1.html
This page clearly says that there is `--clean` flag. Maybe it didn't exist before bundler 2.0? Anyway, there must be some way to trim cache size. Otherwise, it will grow infinitely up to the point when using cache will become slower than not using it. If older bundler doesn't have `--clean`, you can execute `bundle clean --force` separately before storing cache.

**Comment by XhmikosR** [comment]
Both bundler 1.17.3 and 2.1.4 seem to have the clean flag; I've been using it since GitHub Actions first launched last year.

I'd say the least intrusive approach would be to add an option to enable the clean flag, and if time shows more people need this, it could be enabled by default.

**Comment by slonopotamus** [comment]
Hmm...

```
$ bundle install --clean
[DEPRECATED] The `--clean` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set clean 'true'`, and stop using this flag
```

I am using

```
$ bundle --version
Bundler version 2.1.4
```

**Comment by XhmikosR** [comment]
https://github.com/twbs/blog/blob/960cbe0d879a52c7539b714f88b8683dfeb78cb9/.github/workflows/ci.yml#L23

**Comment by eregon** [comment]
I'll try to take a look at this, and make sure it works as expected, both Bundler 1 and 2. No need for an option, as long as it's safe to do.
`bundle config --local set clean true` would set it for all other calls to Bundler, which seems unfortunate, so probably worth trying the explicit command instead, in the case we reuse a cache but the resolved Gemfile.lock changes.

**Comment by eregon** [comment]
`bundle clean` needs to be done after `bundle install`, otherwise:
```
$ bundle clean
Could not find json-2.1.0 in any of the sources
```

So the order is:
```
bundle lock if no Gemfile.lock
bundle install
bundle clean if reusing an existing cache and Gemfile.lock changed

**Comment by XhmikosR** [comment]
Just wondering, can't you always set bundler's clean option to true?

**Comment by eregon** [comment]
That would affect potentially other `bundle ...` commands by the user after, so it seems undesirable.
I have a fix, testing it now.

**Comment by XhmikosR** [comment]
Hence why I initially suggested an option which would set bundler's clean config option to true if set :)

Probably my use case is a pretty simple one, but never had an issue with clean.

Anyway, you should know better :)

**Comment by eregon** [comment]
Fixed in https://github.com/ruby/setup-ruby/releases/tag/v1.53.0, thanks for reporting the issue.
