### ISSUE TITLE
`ruby-head` is coming with bundler-2 out of the box, so `bundler: 1` is basically ignored

### ISSUE THREAD

**Issue by ojab** [ruby/setup-ruby#117]
```
Installing Bundler
  /home/runner/.rubies/ruby-head/bin/gem install bundler -v ~> 1 --no-document
  Successfully installed bundler-1.17.3
  1 gem installed
  Took   0.72 seconds
bundle install
  /home/runner/.rubies/ruby-head/bin/bundle config --local path vendor/bundle
  /home/runner/.rubies/ruby-head/bin/bundle lock
  Fetching gem metadata from https://rubygems.org/...........
  Fetching gem metadata from https://rubygems.org/.
  Resolving dependencies........................................................................
  Bundler could not find compatible versions for gem "bundler":
    In Gemfile.rails-3.x:
      rails (~> 3.0) was resolved to 3.2.15.rc3, which depends on
        bundler (~> 1.0)
  
    Current Bundler version:
      bundler (2.2.0.rc.2)
  This Gemfile requires a different version of Bundler.
  Perhaps you need to update Bundler by running `gem install bundler`?
```

**Comment by eregon** [comment]
This would work fine if you have a checked-in `Gemfile.lock` which was created with Bundler 1.
Is there a reason you specifically want Bundler 1 yet no Gemfile.lock to actually help that?

It seems very inconvenient for anyone using the project if they have to manually `bundle _1_ install/etc`.

In any case, I think Rails 3 has no chance at all to work on ruby-head. I think you'll want at least Rails 5.
Ruby 2.7+ needs Rails 5+ from what I tested (notably kwargs issues and `BigDecimal.new` removed).

**Comment by ojab** [comment]
It's a gem, which is testing various ruby/rails combinations, so no lockfiles are commited & they're generated in CI.
I've made https://github.com/ruby/setup-ruby/pull/118, there is a link to the CI run with woklfow/code there.

**Comment by eregon** [comment]
Forgive me and please correct me if I'm missing something, but I think it makes no sense to test `ruby-head` on Rails 3 & 4.
As you can see, ruby-head fails on Rails 4: https://github.com/ojab/watir-rails/runs/1500872156
I am surprised it even worked on Rails 3 (https://github.com/ojab/watir-rails/runs/1500872128) but probably it's luck that not much of Rails is used by those tests.

And Rails 4's CI doesn't seem to care about ruby-head, which makes a lot of sense, Rails 4 is not officially maintained, and a significant part of the test suite probably never worked on Ruby 2.7+: https://buildkite.com/rails/rails/builds/70569

I guess you're trying to migrate https://github.com/watir/watir-rails/blame/master/.travis.yml.
It probably made sense to test e.g. Rails 4 with ruby-head at that time (seems that line was added ~7 years ago), but I believe no longer.
Nobody should use ruby-head in production with Rails 3/4, right?

Basically what such a CI testing Rails 3/4 with ruby-head do is testing whether some old Rails work with the latest ruby-head, and that is basically guaranteed to fail and be meaningless, because nobody would use such a combination in practice or in production.
So my suggestion is: don't test Rails 3/4 with ruby-head, it doesn't make sense given ruby-head is Ruby 3 now, and the breaking changes are expected, and there is nothing the gem maintainers can do about it (well, unless they decide to maintain Rails 3/4 on ruby-head on their own).

---

The issue with `bundler: 1` on Ruby 2.7+ (and `ruby-head` of course) is valid, and I'll check the PR.
But I'm not sure how relevant it is to fix (and the cost is the extra complexity, longer commands, slower builds, etc), because it's using Bundler 1 from [2018](https://rubygems.org/gems/bundler/versions), which is not guaranteed to work on `ruby-head`, and Bundler 1 seems no longer maintained.

**Comment by ojab** [comment]
Yeah, it doesn't make sense to test `ruby-head` on Rails 3 & 4, I just checking what works and what's not right now on the way to improve specs (to determine _actually_ supported combinations for watir-rails), so it's just an example where the issue manifests itself.
I'll completely understand if you'll decide not to fix it, but it's an issue indeed and IMHO it worth to at least warn (i. e. add annotation to the workflow) if we're using bundler-2 instead of bundler-1 when it was requested.

**Comment by eregon** [comment]
Released in https://github.com/ruby/setup-ruby/releases/tag/v1.56.0

**Comment by eregon** [comment]
FYI there were already 2 issues reported due to this:
* https://github.com/ruby/setup-ruby/issues/119
* https://github.com/ruby/setup-ruby/issues/122

If there is more I think I will revert this change.
It's not worth breaking main use cases, when it's basically already broken for an average user anyway to use any gem requiring Bundler 1 on Ruby 2.7+.
