### ISSUE TITLE
Ancient Ruby Versions

### ISSUE THREAD

**Issue by jfelchner** [ruby/setup-ruby#133]
Hey all, I realize this is an odd request, but there are some very old gems out there that pride themselves on maintaining compatibility with Ruby all the way back to 1.8.  Generally these are very relied-upon "plumbing" libraries.

RSpec is [one of these](https://github.com/rspec/rspec-core/blob/main/rspec-core.gemspec#L32), and my gems [`ruby-progressbar`](https://github.com/jfelchner/ruby-progressbar) and [`fuubar`](https://github.com/thekompanee/fuubar/) are another.  1.8 and 1.9 have long since stopped being supported, but I'd bet I still have users on those versions and as such, I need to keep building against them.

Can we please add support for 1.8.7 and 1.9.0 through 1.9.3?  I would really appreciate it.

**Comment by eregon** [comment]
FWIW, [RSpec 4](https://github.com/rspec/rspec/issues/61) is actually going to drop support such ancient versions. I'd suggest to do the same for other gems too, I think it's not reasonable to ask any maintainer to be compatible with Ruby 1.x after Ruby 3.0 came out.

I don't want to spend time on trying to build these old versions, but you are welcome to try building these versions with https://github.com/ruby/ruby-builder.
I guess it's more realistic on Ubuntu than on macOS. The C compilers are so much more recent though, that it wouldn't surprise me that even if it builds, such old versions would segfault very quickly.
If they build without major hacks or complicating the workflow too much, and they pass the tests in that workflow, and most of their test suite (`make test-all`), and the existing bundler caching logic works fine on them, then I'll consider adding them to ruby/setup-ruby.

On Windows, RubyInstaller builds for those versions [exist](https://rubyinstaller.org/downloads/archives/), but I don't know if they still work.

Closing because I think 1) this is not worth the effort, 2) maintainers of this action have no intention to try to build such ancient versions.

**Comment by eregon** [comment]
For testing against such old versions, using Docker images might the far easier way.

**Comment by jfelchner** [comment]
Totally get it @eregon.  No hard feelings.  Thanks for responding and for making this action easy to use. ❤️

**Comment by pboling** [comment]
The problem with dropping support for old versions of Ruby, for any gem following Semantic Versioning, it requires bumping to a new major version number, and often the next version isn't ready to drop, and prepping a full major release without the "not-ready" stuff, is much more work for small teams of maintainers.  I have this problem on the `oauth2` gem, which isn't a small effort.

**Comment by eregon** [comment]
I think this is actually not such a clear cut. But it's also likely quite an open topic of discussion in general.
What follows is just my opinion. I must say I don't have lots of experience in the domain.
IMHO there is no need for a new major gem version for dropping an unsupported end-of-life Ruby version.
People running unsupported end-of-life Ruby versions must pin all gems (e.g., with a Gemfile.lock), otherwise it would never work.

I would think it's enough to set the `required_ruby_version` in the `.gemspec`, and use a new minor version bump for good measure. Then even `bundle update` on old versions shouldn't pick the newer version.

Almost no maintainer has time to maintain versions as old as Ruby 1.8, and IMHO they shouldn't. If people want to run things on Ruby 1.8 then IMHO they should accept the responsibility of maintaining every single gem they depend on or accept to never have updates or fixes for their gem dependencies.

**Comment by eregon** [comment]
If you do want to test on such old versions, as mentioned above you can use Docker images.
This is what RSpec does: https://github.com/rspec/rspec-core/blob/ea8554afd1a2b63677c6593059fa8f2476181deb/.github/workflows/ci.yml#L70-L108
