### ISSUE TITLE
Include `libruby.a` and `libruby-static.a`

### ISSUE THREAD

**Issue by ianks** [ruby/setup-ruby#142]
I have a gem that that needs to have `libruby.a` and `libruby-static.a` to precompile a static binary. Unfortunately, it does not seem that this is available by default with the current build. Not sure the best way to do this, but it would be nice to have both the dylib and static lib available for building extensions if possible :smile:

**Comment by eregon** [comment]
Which gem is it? Is there a reason the shared libruby cannot be used?

`--enable-shared` is used since https://github.com/ruby/setup-ruby/issues/43.
I'm not sure we can have both, what ./configure flags would be needed?

Also, there is the concern that this would significantly increase the download size.

**Comment by ianks** [comment]
maybe we could have another build like `2.7-static` or something? in this case, i want to precompile rust binaries so users don’t have to have rustc/ cargo installed.

**Comment by eregon** [comment]
I'm not willing to double the numbers of builds, it's already many and takes a while.
Could you simply build Ruby in your CI if you have such specific needs?
Also when embedding Ruby you might also want other flags, etc.
It's not hard to build Ruby really (https://github.com/ruby/ruby#readme, basically `./configure --prefix=...; make; make install`), especially Ruby >= 2.4 which doesn't need an old OpenSSL.
