### ISSUE TITLE
Randomly getting "string contains null byte" without code change

### ISSUE THREAD

**Issue by destroytoday** [ruby/setup-ruby#161]
👋  Hi! My Ruby github actions workflow randomly started failing, despite no code changes. My tests immediately throw `string contains null byte`. I noticed this because I’ve been working in a branch and that started failing even though I was only working with JS. Then all my dependabot PRs started failing with the same error. I haven’t updated master since it successfully passed, so I pushed an empty commit to test CI for it and _now_ I get that same error whereas it was fine before. Any ideas? or has anyone else experienced this? I know it’s related to encoding, but I tried all sorts of env vars to force UTF8 with no luck. I’m guessing it’s gotta either be something with the workflow actions or somehow on the infra side.

**Comment by eregon** [comment]
`string contains null byte` is an exception raised by Ruby.
I don't think this action can possibly cause that.
Maybe something else changed in the [environment](https://github.com/actions/virtual-environments)/CI image.
https://github.community/c/code-to-cloud/github-actions/41 is a better place to ask about this.
I'll close because I don't there is anything this action can do about it.

**Comment by destroytoday** [comment]
Thanks, Benoit. I’ll try there.
