### ISSUE TITLE
Ruby 1.9 support

### ISSUE THREAD

**Issue by mullermp** [ruby/setup-ruby#204]
Hello! I am wondering if it's possible to support Ruby 1.9. It doesn't appear to be supported (available versions are 2.0+). Some of our projects unfortunately still support Ruby 1.9 and we'd like to test against it where possible.

The last release is here: https://www.ruby-lang.org/en/news/2014/11/13/ruby-1-9-3-p551-is-released/

**Comment by eregon** [comment]
Sorry, no, 1.9 is too old, I think it's high time to drop support for it.
You can try to build it with https://github.com/ruby/ruby-builder if you want to try.

You can potentially use Docker images if you need such ancient Ruby versions.

**Comment by mullermp** [comment]
Unfortunately we can't drop support for it - we own the AWS SDK For Ruby and customers (even internal) still use it. Just to push back a bit - why support Ruby 2.0 or 2.1 in `setup-ruby` then - aren't those old too?

**Comment by mullermp** [comment]
I can create a PR if that helps. I think it's worthwhile to support as long as you are supporting Ruby 2.0, 2.1, 2.2, 2.3 etc like other end of life rubies.

**Comment by eregon** [comment]
Ruby 2 is a symbolic barrier that I think is worth making it clear it's the strict minimum version.
Consider 2.0 - 2.3 as only partially supported, e.g, a system package (e.g. database) linking against the system libssl (only libssl 1.1 available on modern OS) would not work with them since they need libssl 1.0 which is out of life, in other words they are insecure and they have known security issues.

1.8.7 is likely impossible to build on any modern OS.
1.9 not sure, you are welcome to try and report the results.

**Comment by mullermp** [comment]
I agree on having a symbolic barrier for a strict minimum version - you have to draw the line somewhere! My opinion is that 1.9.3 should be that barrier because IIRC it broke some syntax from 1.8.7 but 2.0.0 is the same as 1.9.3 with added new backward compatible capabilities (such as keyword arguments). I also think that it uses the same OpenSSL as 2.0 to 2.3.

**Comment by mullermp** [comment]
I got 1.9.3 to build! I had to fork a number of packages. On [this pull request](https://github.com/mullermp/ruby-builder/pull/1/checks) you can see that build ruby step succeeds however the CI fails on installing json.

Here's what I did:

I first [blindly added 1.9.3](https://github.com/mullermp/setup-ruby/commit/24718203832a60731c48c91bf165f1341b094d78) to a fork of `setup-ruby` here. I tried to [use the fork in one of our repos](https://github.com/aws/aws-sdk-ruby-record/pull/118/checks?check_run_id=3164479180). I found that binaries are downloaded from [your release page](https://github.com/ruby/ruby-builder/releases/tag/toolcache) and I needed to generate one for 1.9.3.

I forked `ruby-builder` and [added support for 1.9](https://github.com/mullermp/ruby-builder/pull/1/) and had to [modify `has_broken_mac_openssl` function](https://github.com/mullermp/ruby-build/commit/34eae1efe6a2dd3301dab10fb22c6e0e7306487f) in a fork of `ruby-build`.

**Comment by mullermp** [comment]
CI fails on `Error: request to https://uploads.github.com/repos/ruby/ruby-builder/releases/33599578/assets?name=ruby-1.9.3-p551-ubuntu-18.04.tar.gz& failed, reason: socket hang up` but I think this is permissions based.

**Comment by mullermp** [comment]
@eregon I am wondering if you will reconsider opening this. I have all the code changes out. Supporting this is fairly minimal and similar to 2.0 to 2.3, and helps other teams test old Ruby versions.

**Comment by eregon** [comment]
Did you see that 1.9.3 built properly in GH Actions?
You can just remove/comment the `Check if already built` step for that purpose.

**Comment by mullermp** [comment]
Yes, it built properly. You can see the build log here: https://github.com/mullermp/ruby-builder/pull/1/checks?check_run_id=3165246747

**Comment by eregon** [comment]
OK, thanks, I'll take a look at your PRs and if everything works well I'll add 1.9.3, https://github.com/ruby/setup-ruby/issues/204#issuecomment-886960644 is a fair point.

**Comment by eregon** [comment]
FWIW, 1.9 has quite a few issues that 2.0+ does not have.
Issues found while trying to add support for 1.9, due to really old RubyGems and OpenSSL C ext:
* `--no-document` is not supported on 1.9, `--no-ri --no-rdoc` is needed instead. Similar issue for ~/.gemrc.
* `gem install json:2.2.0` does not work, one needs `gem install json -v 2.2.0`.
* `OpenSSL::OPENSSL_LIBRARY_VERSION` is not defined (the loaded libssl version)
* There are no 64-bit builds of 1.9 on Windows. So no 1.9 on Windows, I'm not willing to support 32-bit builds on Windows just for 1.9.

**Comment by eregon** [comment]
Released as https://github.com/ruby/setup-ruby/releases/tag/v1.79.0

**Comment by mullermp** [comment]
Thank you!!! I hope most of my changes were useful.

Not at all worried about Windows support. :)
