### ISSUE TITLE
jruby-9.3.0.0 is released but not supported

### ISSUE THREAD

**Issue by klobuczek** [ruby/setup-ruby#220]

**Comment by eregon** [comment]
First JRuby 9.3.0.0 needs to be added to https://github.com/rbenv/ruby-build, feel free to make a PR there

**Comment by headius** [comment]
Perhaps we should add a ruby-build PR to our release process? @enebo

**Comment by headius** [comment]
See https://github.com/ruby/pp/pull/4/checks?check_run_id=3696208906 for a build that wants 9.3 but it is not there yet.

**Comment by eregon** [comment]
@headius @enebo Yes I think it would be great if you could make a PR to ruby-build after a release.
ruby-build is already listed in https://github.com/jruby/jruby/wiki/JRubyDistributions
I'll do it this time, but it would be great if I only have to care about the setup-ruby part, not an extra ruby-build PR too.

**Comment by eregon** [comment]
@headius @enebo Actually I'll let you do it, because some of it is unclear to me.
For instance ruby-build seems to still use https://s3.amazonaws.com/jruby.org/downloads but not sure that's good now, and whether `jruby-bin-${version}.tar.gz` or `jruby-dist-${version}-bin.tar.gz` should be used.
ruby-versions had a recent change about this in https://github.com/postmodern/ruby-versions/commit/bc2c48474760fdd635a1870cdac60146fd37c51c

**Comment by eregon** [comment]
I added jruby 9.3.0.0 to ruby-build from https://s3.amazonaws.com/jruby.org/downloads/9.3.0.0/jruby-bin-9.3.0.0.tar.gz in https://github.com/rbenv/ruby-build/pull/1797 and I verified it's the same as https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.3.0.0/jruby-dist-9.3.0.0-bin.tar.gz.

Is it OK to keep using s3.amazonaws.com or should the URLs be updated to use maven? If the later make a PR to adjust that globally in ruby-build.

**Comment by headius** [comment]
@eregon Thank you.

The maven URLs would be preferable. We continue to maintain the S3 URLs as a courtesy to packages and apps that use them but have been trying to switch everyone to maven.
