### ISSUE TITLE
Prebuilt rubies are using an outdated libyaml that has a "trailing space" bug.

### ISSUE THREAD

**Issue by urkle** [ruby/setup-ruby#243]
In a gem that I am testing using this GH action to install ruby I noticed a very odd behavior when testing code that generated a YAML file.  On my local machine it worked fine, but in GH Actions it failed due to an extra trailing space in the output of keys with nil as the value.  This issue was fixed in libyaml 0.2.5

libYaml bug report: https://github.com/yaml/libyaml/issues/46

I am using the MRI rubies (2.5, 2.6, 2.7, and 3.0 ALL have this issue).

Now, I am unsure if the issue is with the MRI rubies installed by this action OR with the "host" ubuntu-latest that GH uses as the runner.

Failed run: https://github.com/SchemaPlus/schema_dev/actions/runs/1565095483
Succeeding run: (with hack in the gem to trim the spaces) https://github.com/SchemaPlus/schema_dev/actions/runs/1565125434

**Comment by MSP-Greg** [comment]
1. Ruby's Psych bundles/vendors libyaml, but libyaml 0.2.5 was only included in Psych 3.2.0 and later.  Ruby 2.7 used Psych 3.1.0, Ruby 3.0 used 3.3.2.

2. I think Ubuntu 20.04 is using libyaml 0.2.2 (Windows WSL2/Ubuntu does).

3. Ruby can be built with the bundled libyaml files, but the `--enable-bundled-libyaml` needs to be passed to `configure`.

I think the flag can be set when installing the Psych gem.  Not sure about bundler, I think it can...

**Comment by eregon** [comment]
You can request at https://github.com/actions/virtual-environments to update to a more recent libyaml, but it might not be accepted if e.g. the libyaml is just the one shipped with Ubuntu.

I don't want to rebuild all Rubies with `--enable-bundled-libyaml` just for this issue, it's a lot of work and this option is not default so it's likely to happen on user machines too. And it could introduce other differences which might not be expected.
If the libyaml in GH images is updated though that would make for a good reason to rebuild.

Probably the most pragmatic solution here is to workaround at a different level, so it also works on machines with a system libyaml < 0.2.5.
Installing psych explicitly and with `--enable-bundled-libyaml` seems a great solution.

I'll close because I don't think there is anything actionable here.

**Comment by WaKeMaTTa** [comment]
Workaround: https://github.com/actions/runner-images/issues/6094#issuecomment-1216637809
