### ISSUE TITLE
Add version in Actions log?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#284]
In setup-ruby-pkgs, I added code to log the version be used, see:

https://github.com/ruby/openssl/runs/4973490572?check_suite_focus=true#step:3:43

It is redundant, as the 'Set up job' step does the show the commit, like:
```
Download action repository 'ruby/setup-ruby@v1' (SHA:fabf2515e6b5531555983e2641f2acdf622b0e50)
```

The code used is (in the common.js file):
```js
export const version = JSON.parse(fs.readFileSync(`${__dirname}\\package.json`, 'utf8')).version
```

And it does require syncing the version in `package.json`, which is a common practice, as many of the actions repos keep it in sync.

As seen recently, given that Actions can be a bit brittle due to RubyGems/Bundler issues, having the version 'right there', instead of requiring one to deal with SHA's is helpful when 'unexpected results' occur.

Note that I don't consider RubyGems/Bundler issues to be a fault of those repos, it's just due to the huge matrix of versions that may or may not work correctly, which may also be affected by other dependencies, as we saw with the 'Pysch in Gemfile' problem...

Just a thought. I can do a PR, or never mind...

**Comment by eregon** [comment]
I know you mean well, but I think this would introduce an overhead as I would need to update that versions somehow when making a release, or automate that, and there is the risk it could be inconsistent which would be bad. And any overhead for releasing is unacceptable, because it's already too much manual work for like a 100 releases I did so far.
Also the sha is more precise, so I think it's good enough as-is.
