### ISSUE TITLE
bundler: <version> is not respected

### ISSUE THREAD

**Issue by pboling** [ruby/setup-ruby#327]
This [workflow](https://github.com/rubocop-semver/rubocop-ruby2_2/runs/6248238848?check_suite_focus=true) should be using a specified version of `bundler`, in this case `1.16.6`, but instead it attempts an install of `~> 1.0`, seemingly ignorant of the configuration.
The install attempted is the same command as in https://github.com/ruby/setup-ruby/issues/326, which is very _sus_.
```
/opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem install bundler -v ~> 1.0
```
Result:
```
Installing Bundler
  Bundler 2 requires Ruby 2.3+, using Bundler 1 on Ruby <= 2.2
  /opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem install bundler -v ~> 1.0
  ERROR:  Error installing bundler:
  	"bundle" from bundler conflicts with /opt/hostedtoolcache/Ruby/2.2.10/x64/bin/bundle
  Took   0.66 seconds
Error: Error: The process '/opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:3454:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:3437:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:3331:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by MSP-Greg** [comment]
There was some discussion about adding a rubygems input and its effect on the bundler input.  Or, using both may not be a good idea.

Hence, for now, I suspect you'd be best to use 'none' for the bundler input...

**Comment by eregon** [comment]
`bundler: none` will however not use `bundler-cache` even if it's set, because `bundler: none` means "I don't need Bundler".

The error itself is most likely a bug of that RubyGems version, it should allow to install bundler 1 (again) fine.

I guess we could skip installing bundler if the rubygems input is set, and the bundler input is `default`.

@deivid-rodriguez Do all versions of RubyGems install Bundler as well on `gem update --system [VERSION]`, and are they all careful to e.g. not install Bundler 2 on a old Rubies which can't use it?

**Comment by eregon** [comment]
My previous reply applies mostly to https://github.com/ruby/setup-ruby/issues/326, I thought it was the same issue but renamed.

For the issue that the given Bundler version is ignored here, that's a clear bug.

**Comment by pboling** [comment]
After I made these issues it occurred to me that there are two ways of interpreting `bundler: default` -

1. Use whatever came with rubygems, or the docker image, or whatever was pre-existing.
2. Install and use the "default" value that rubygems comes up with based on its understanding of `RUBY_VERSION` and `RUBY_ENGINE` when executing `gem install bundler` with no version constraint.

Neither of these is happening, but I would posit that both options are useful.
`bundler: none` does have a similar effect to Option 1 above, except, as @eregon pointed out, it prevents `bundler-cache` from being used.

So perhaps there are more terms, and implementation, needed to give the various options people would want.

**Comment by deivid-rodriguez** [comment]
> @deivid-rodriguez Do all versions of RubyGems install Bundler as well on `gem update --system [VERSION]`, and are they all careful to e.g. not install Bundler 2 on a old Rubies which can't use it?

Regarding the first question, not sure, this behavior was there even before I started maintaining RubyGems and Bundler, but I can't tell exactly when it was first introduced without checking. Regarding the second question, yes, it should always install a compatible version.

**Comment by MSP-Greg** [comment]
> Do all versions of RubyGems install Bundler

A quick check, looks like Bundler is only installed for `gem update --system` 2.6 and later. 2.6.14 work with Rubies `>= 1.8.7`

> Maybe a new value to mean "use the bundler already installed (from Ruby or RubyGems update)" makes sense, it would be like none but allow bundler-cache, and maybe fail if there is no bundler installed. Not sure it's really needed though. Not sure of a good name for it either.

Maybe 'rubygems' which disables bundler installation (and defaults to the Bundler version installed?

**Comment by pboling** [comment]
## Proposal: Additional Options

I propose additional options, and making "default" synonymous with one of them, such that the complete set of options is as follows:

| option             | bundler-cache available | gem install                                                 | description                                          |
|--------------------|-------------------------|-------------------------------------------------------------|------------------------------------------------------|
| "rubygems"         | yes                     | no                                                          | Use what came with Rubygems, if any                  |
| "ruby"             | yes                     | no                                                          | Use what came with Ruby, if any                      |
| "system"           | yes                     | no                                                          | Use what came with docker image / system, if any     |
| "latest"           | yes                     | `gem install bundler` (no version constraint)               | \* perhaps the logic driving current ~> 1 constraint |
| "Gemfile.lock"     | yes                     | `gem install bundler -v <version parsed from Gemfile.lock>` | use whatever is specified in Gemfile.lock            |
| `<version number>` | yes                     | `gem install bunder -v <version number>`                    | Use specified version number                         |
| "none"             | no                      | no                                                          | NOOP                                                 |

\*  are there bugs in `bundler `gem's minimum ruby requirement that necessitate the current `~> 1` logic?

## Which one would be best as synonymous with default?

Since it doesn't do what I consider intuitive for "default" currently, I think it would be a breaking change regardless, for some action workflows currently using "default".

I agree with @MSP-Greg, I think a switch to having `default` be synonymous with `rubygems` is the closest to the principle of least surprise.  This is what I was expecting it to do originally.

**Comment by MSP-Greg** [comment]
1. Maybe it's time to consider a jump to v2.

2. The 'bundler-cache' input defaults to `false`, and the only other allowed value is `true`.  So, it can be independent of the other inputs, and if one runs `bundle install` without a copy of Bundler, it errors.

3. Rather than adding multiple inputs to the 'bundler' input, maybe the following:
    * Add a 'noop' input, which forces 'don't install bundler' (using the default version or the one installed by `gem update --system`)
    * If the 'rubygems' input is specified and a 'bundler' input is not, Bundler will be installed if a file/ENV specifies its version, otherwise no install of Bundler will occur.
    * If a numeric version or `latest` is specified for 'bundler', it will be installed, regardless of the 'rubygems' input value.
    * Remove `none` as an allowed value for the 'bundler' input.
    * I'm not sure if the input value of `Gemfile.lock` is needed for the 'bundler` input.  Should it be automatic if the info is specified?

**Comment by eregon** [comment]
1. No, it's too annoying to update to a major version and this is an edge case/small bug (rubygems input didn't exist for long)
2. True, bundler-cache could always be decided independently of the bundler input, given the current default of `false` (and probably unlikely to change)
3. I don't think we need to add anything currently, it would only make things more complicated

> I agree with @MSP-Greg, I think a switch to having `default` be synonymous with `rubygems` is the closest to the principle of least surprise. This is what I was expecting it to do originally.

No, because then it could pick a wrong Bundler version, or force installing yet another Bundler version at runtime when there is a lockfile.
And almost all workflows need Bundler, so no bundler by default for Ruby < 2.6 makes no sense.
I believe the default behavior is already what 99% want, and we have no need to change that.

We just need to fix the interaction of the `rubygems`, `bundler` and `bundler-cache` inputs, I'll do that when I get some time.

**Comment by eregon** [comment]
I forgot but `bundler-cache` is already independent of the `bundler` input since https://github.com/ruby/setup-ruby/commit/fabf2515e6b5531555983e2641f2acdf622b0e50.
So `none` should work for your use-case here @pboling.
And setting `rubygems` should affect `bundler: default` to behave like `bundler: none` in that case.
