### ISSUE TITLE
No JRuby 9.3.6.0 on Windows 2022?

### ISSUE THREAD

**Issue by dentarg** [ruby/setup-ruby#356]
From https://github.com/dentarg/dyno_metadata/runs/7219851913?check_suite_focus=true#step:3:32

```
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/jruby-9.3.6.0-windows-latest.tar.gz
  Took   0.21 seconds
Error: Error: Unexpected HTTP response: 404
    at D:\a\_actions\ruby\setup-ruby\v1\dist\index.js:7561:[25](https://github.com/dentarg/dyno_metadata/runs/7219851913?check_suite_focus=true#step:3:32)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\ruby\setup-ruby\v1\dist\index.js:7471:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Looks like some jobs failed for https://github.com/ruby/setup-ruby/pull/353:

- windows-2022 jruby https://github.com/ruby/setup-ruby/runs/7090551641?check_suite_focus=true#step:3:29
- windows-2022 jruby-head https://github.com/ruby/setup-ruby/runs/7090551737?check_suite_focus=true#step:3:85

Is that the cause?

**Comment by eregon** [comment]
Ah yes probably, because the job building the windows archive failed:
https://github.com/ruby/ruby-builder/runs/7080808967?check_suite_focus=true

The issue is JRuby on Windows doesn't work recently, for multiple reasons: https://github.com/ruby/setup-ruby/issues/339
jruby-head is completely broken for instance: https://github.com/jruby/jruby/issues/7106
And I'd like to avoid too much workarounds and let them fix it upstream.

**Comment by eregon** [comment]
JRuby 9.3.6.0 windows is built now: https://github.com/ruby/ruby-builder/runs/7231464594?check_suite_focus=true
