### ISSUE TITLE
Honor default.run.working-directory?

### ISSUE THREAD

**Issue by nirvdrum** [ruby/setup-ruby#54]
I'm currently working on a mono repo project where there's a Rails application in one subdirectory and a React application in another. We have workflow files for each project and change the default working directory so all commands run in the correct path:

```
defaults:
  run:
    working-directory: rails_app
```

It would be nice if this action could read in that value rather than having me duplicate it in the action's `with` clause, in order for the _.ruby-version_ file to be found. I've never looked at the GitHub Actions API, so apologies if I'm asking for something that isn't doable.

**Comment by eregon** [comment]
Thanks for the report.
I see, that's the new way to set a working-directory for all steps:
https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/

I would think these defaults only apply to `- run:` steps and not `- uses:` steps, so I don't think there is anything this action can do about this.

I agree ideally it would just work, based on per-job or per-workflow `working-directory` setting.
Maybe
```yaml
defaults:
  working-directory: rails_app
```
would work? I'm not sure.

In any case, this seems best asked on the GitHub Actions forum at https://github.community/t5/GitHub-Actions/bd-p/actions. I'm happy to follow the discussion there if you post a link.
I'll close this issue because I don't think there is anything we can do in this action.

**Comment by eregon** [comment]
Alternatively I guess this is an issue related to https://github.com/actions/runner/issues so it could also be filed there.

**Comment by nirvdrum** [comment]
Okay, thanks. I wasn't sure if the API had a KV lookup that you could use without having to have the values cascade. While it is defined for `run`, I can't think of a reason why someone would want to have their _.ruby-version_ file in a directory other than the the one they want to run in. I'm sure it happens, but I'd think that'd be the exception rather than the rule.

**Comment by MSP-Greg** [comment]
I opened https://github.com/actions/runner/issues/467, which asks for the working-directory path to be exposed as an env variable.
