### ISSUE TITLE
setup-ruby interferes with Windows runner's own MSYS2 install

### ISSUE THREAD

**Issue by lopopolo** [ruby/setup-ruby#57]
https://github.com/ruby/setup-ruby/blob/002b15eeca2c8a043d93bfd8bd5acd44761954f9/windows.js#L121-L124

https://github.com/actions/virtual-environments/issues/905#issuecomment-631741076

I believe it is time to remove this bit of setup. If it is not, how can I opt out of setup-ruby including a bundled MSYS2?

**Comment by MSP-Greg** [comment]
@lopopolo

See my response in https://github.com/actions/virtual-environments/issues/905.

Re changes here, there are quite a few repos running Windows CI, and having MSYS2 in the path is essentially expected.  An input could be added to allow it not to be so, but I think the better fix is to remove 7z from the MSYS2 install...

**Comment by eregon** [comment]
That specific case seems a bug of upstream:
https://github.com/actions/virtual-environments/issues/905#issuecomment-631872617
https://github.com/actions/virtual-environments/pull/916

The linked code will actually do nothing now, right? Since C:\msys64 will exist (but it's likely not rolled out everywhere yet so we need the fallback).

I guess the only to do is we shouldn't prepend `C:\msys64\mingw64\bin` and `C:\msys64\usr\bin` to the PATH if `C:\msys64` already exists, and if MSYS2 is already in the PATH.
That way the PATH is closer to what it looks like when the runner starts.
But from what I heard MSYS2 isn't added to PATH by default, so I guess no changes at all?

**Comment by eregon** [comment]
I tried to make sure my assumptions regarding PATH are correct in https://github.com/ruby/setup-ruby/runs/695926638?check_suite_focus=true
But that revealed C;\msys64 doesn't exist in that run and so is not yet fully deployed.

**Comment by eregon** [comment]
When there is no C:\msys64 in the image, the 7z from Chocolatey is used (both before and after this action):
https://github.com/ruby/setup-ruby/runs/695968983?check_suite_focus=true

**Comment by MSP-Greg** [comment]
> I guess no changes at all?

Agreed.

**Comment by MSP-Greg** [comment]
JFYI, the comment below is incorrect.

The code should be removed when Actions removes the embedded MSYS2 installs that currently exist in the four ToolCache Rubies.

When that happens (only after MSYS2 install is rolled out), there will be nothing to symlink to.

```
// Remove when Actions Windows image contains MSYS2 install
```
