### ISSUE TITLE
Ruby version should be read from Gemfile.lock by default

### ISSUE THREAD

**Issue by benlangfeld** [ruby/setup-ruby#590]
Similarly to https://github.com/ruby/setup-ruby/issues/38, the version of Ruby to be installed can be specified in `Gemfile.lock` via `RUBY VERSION` directive. This should be used the same way `.ruby-version` and `.tool-versions` are, for applications which lock their Ruby version using the `Gemfile.lock`, so as to avoid duplication and possible divergence.

Note to self, relevant functions:
* https://github.com/ruby/setup-ruby/blob/1198b074305f9356bd56dd4b311757cc0dab2f1c/index.js#L108-L141
* https://github.com/ruby/setup-ruby/blob/1198b074305f9356bd56dd4b311757cc0dab2f1c/bundler.js#L30-L49

**Comment by eregon** [comment]
That sounds reasonable, I think the Gemfile.lock should be checked last, i.e. the other 2 files should have precedence.
PR welcome.

**Comment by benlangfeld** [comment]
> That sounds reasonable, I think the Gemfile.lock should be checked last, i.e. the other 2 files should have precedence. PR welcome.

Yep, will prep one today or next week :)

**Comment by eregon** [comment]
TBH considering the time spent to review [the PR](https://github.com/ruby/setup-ruby/pull/592), I wonder whether the feature is even worth it at all.

Gemfile supports `ruby file: ".ruby-version"` so this can deduplicate the information: https://bundler.io/v2.5/man/gemfile.5.html#VERSION-required-
And that has the advantage a Ruby switcher can also automatically use the right version, no Ruby switcher looks in `Gemfile/Gemfile.lock` for the ruby version AFAIK.

**Comment by benlangfeld** [comment]
> TBH considering the time spent to review https://github.com/ruby/setup-ruby/pull/592, I wonder whether the feature is even worth it at all.

**Comment by eregon** [comment]
I am sorry it went this way, to be clear I did not close the PR and I am not against it, but we should discuss the merit of this feature based on the the second paragraph in https://github.com/ruby/setup-ruby/issues/590#issuecomment-2096551854 first. I didn't realize that before, otherwise of course I would have brought it up before the PR.

I think you should also consider the maintainers point of view and how much time I spent on this.
I do not want endless discussions about preference of whitespace trimming and what not, especially when it is actually intended and significant.
My POV is you act like you know better about a bunch of things but I wrote like 90% of this project, so I think I know better and I have more context about this project, and yet in the review you force me to explain things in lots of details (a big time investment). That is frustrating, and I think contributors should be mindful of the time investment of maintainers and try to minimize it.

**Comment by benlangfeld** [comment]
I didn't force you to go into great detail on anything, I followed your request to split two different issues with this project out into distinct PRs where you could choose to engage with them or not, and you opted to be rude and dismissive because someone dared to have an opinion that differs from yours.

Thank you for your efforts and have a good day.

**Comment by richardkmichael** [comment]
I was wondering why the action didn't read from `Gemfile.lock`, searched the project and issues and found this.

I prefer not to commit, or rely on, tool-specific (`.ruby-version`) files to "indirectly" specify the Ruby version of a project.  `Gemfile.lock` captures all the dependencies; gems, Ruby version, etc.  It's definitive, and I'm surprised it's not the *default* source for the action.

It seems strange this was rejected.

**Comment by gaffneyc** [comment]
I agree that `setup-ruby` should support reading from either Gemfile or Gemfile.lock. Since Bundler is _the_ idiomatic way to specify gem dependencies and required Ruby version for apps it's odd to support several alternative tools (.ruby-version, .tool-version., mise.toml) but not the one supplied by Ruby itself.

> no Ruby switcher looks in Gemfile/Gemfile.lock for the ruby version AFAIK.

[Mise currently supports](https://mise.jdx.dev/lang/ruby.html) reading from the Gemfile / Gemfile.lock

**Comment by eregon** [comment]
> [Mise currently supports](https://mise.jdx.dev/lang/ruby.html) reading from the Gemfile / Gemfile.lock

It would be interesting to see how Mise parses Gemfile / Gemfile.lock.
But none of the other Ruby version switchers do, and that's because AFAIK the Gemfile / Gemfile.lock is not the canonical place to specify the Ruby version, `.ruby-version` is (which is *not* tool-specific, that's the one supported by most Ruby switchers).

In fact trying to get the version from the Gemfile is particularly brittle and would only work if it's something as simple as `ruby '2.3.4'` or `ruby "2.3.4"` (but could also wrongly get that from inside a `=begin/=end` comment) but wouldn't (reasonably) for `ruby %{2.3.4}` or anything more dynamic, including `ruby file: ".ruby-version"`. You'd need to execute the Gemfile as Ruby code to know, and that's clearly a cyclic issue that can't be solved reasonably.

Reading from Gemfile.lock is simpler, but many usages don't commit Gemfile.lock, and it introduces another cyclic dependency: RubyGems and Bundler are concerns *after* installing the Ruby version, not before, e.g. the default version of Bundler to use depends on the Ruby version. https://github.com/ruby/setup-ruby/pull/592 is incorrect in that it assumes it's always just `Gemfile.lock` but it can be other lockfiles. We'd need to `bundler.detectGemfiles()` before choosing the Ruby version which feels wrong and could become problematic if e.g. detectGemfiles() would need to depend on the Bundler version in the future.

I don't want to discuss more on this issue, so I will close and lock it.
If all these concerned are addressed with respect and understanding the concerns I wrote, and a good PR requiring little work from my part is opened, I may accept it.
