### ISSUE TITLE
Faild in ubuntu-24.04 runner

### ISSUE THREAD

**Issue by kachick** [ruby/setup-ruby#595]
Ubuntu 24.04 runner has been released. 

https://github.com/actions/runner-images/issues/9848

But, attempting to use it resulted in the following errors.

```
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
In such a case, you should install Ruby in the $RUNNER_TOOL_CACHE yourself, for example using https://github.com/rbenv/ruby-build
You can take inspiration from this workflow for more details: https://github.com/ruby/ruby-builder/blob/master/.github/workflows/build.yml
$ ruby-build head /opt/hostedtoolcache/Ruby/head/x64
Once that completes successfully, mark it as complete with:
$ touch /opt/hostedtoolcache/Ruby/head/x64.complete
It is your responsibility to ensure installing Ruby like that is not done in parallel.
```

**Comment by eregon** [comment]
1.9 fails to build: https://github.com/ruby/ruby-builder/actions/runs/9148390417/job/25150867207
The rest seems to build fine.

I'll only add the latest releases of JRuby and TruffleRuby for now on 24.04, we can add more later.

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.177.0
Some -head builds still need to be fixed, some of them waiting on https://github.com/actions/runner-images/issues/9895.

**Comment by Bo98** [comment]
Is the double 1.177.0 intentional? https://github.com/ruby/setup-ruby/tags

Seems to make Dependabot error

**Comment by eregon** [comment]
Ah damn that's what I get from doing a release on a phone. Will fix.

**Comment by 0nyr** [comment]
Hello. I get this exact error on my blog, when trying to deploy to GitHub Pages: [see here](https://github.com/0nyr/onyr-website/actions/runs/11202317317/job/31138277222). It's strange because it works fine on another website of mine with the exact same (default) workflow .yml file, so I have no idea of what is wrong and if it is on my side or not. Here is my repo: [my repo](https://github.com/0nyr/onyr-website) any help appreciated.

**Comment by kachick** [comment]
@0nyr

https://github.com/ruby/setup-ruby/pull/596 was released in https://github.com/ruby/setup-ruby/releases/tag/v1.177.0

Your workflow is using older version https://github.com/0nyr/onyr-website/blob/3171828ebdd19cce6c8251730a7e6e72019e57d2/.github/workflows/jekyll.yml#L37

```yaml
uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
```

How about to try updating?

For example.

```yaml
uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 # v1.195.0
```

**Comment by 0nyr** [comment]
@kachick You are a blessing. Many thanks. How can I know where to get this information the next time ?

**Comment by jwillemsen** [comment]
I would use `ruby/setup-ruby@v1` as uses, and add a dependabot.yml to use github actions to keep the used actions up to date

**Comment by kachick** [comment]
Guessing your candidates

- Just using latest for the major version as `ruby/setup-ruby@v1` # [official recommendation](https://github.com/ruby/setup-ruby/blob/f6e05710eced3c9c28e489afdc6fd8a3bc685325/README.md#L238-L248)
- `ruby/setup-ruby@v1` as above with bumping dependabot or renovatebot # jwillemsen wrote
- Current git hash style with bumping dependabot or renovatebot # I prefer, but I don't recommend this for others

**Comment by jwillemsen** [comment]
See https://github.com/RemedyIT/axcioma/blob/master/.github/dependabot.yml

**Comment by vincerubinetti** [comment]
In my repo [lab-website-template](https://github.com/greenelab/lab-website-template), I use a pinned version number. I know I wouldn't have done it without a reason, because I always use latest major (e.g. `v1`) for actions, and do so for all of the other actions in that repo. I seem to recall that this package doesn't make a tag for the exact string "v1" pointing to the latest tag, and I couldn't get it to run without an exact version? Is that actually the case?

FYI to users who are not aware... GitHub Actions doesn't do any sem-ver when installing/using a third-party action. That is, if you specify `v1` or `v1.*.*` or whatever, GitHub won't automatically find e.g. `v1.92.0`, it just looks for a tag with the _exact_ name "v1". So it's basically up to action maintainer to re-tag things after each update so e.g. `v1` points to `v1.92.0`.

**Comment by Bo98** [comment]
> it just looks for a tag with the _exact_ name "v1"

GitHub Actions also looks for branches and that's what this action uses so `v1` should work fine.

Which you use is up to you. Some people prefer exact versioning with auto bumping from Dependabot for better control. Some people prefer the lower maintenance requirement of `v1`.
