### ISSUE TITLE
Cannot install the `actiontext` gem with Rails 7.1 and Ruby 3.1/3.2 on the Ubuntu 22.04 runner

### ISSUE THREAD

**Issue by oliverklee** [ruby/setup-ruby#602]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/lwe/page_title_helper/actions/runs/9157727571/job/25246440277?pr=186

### Any other notes?

- This problem only occurs on the new Ubuntu 24.04 runners, not with the Ubuntu 22.04 runners.
- This problem only occurs on Ruby 3.1.5 and 3.2.4, not on Ruby 3.3.1.
- This problem only occurs with Rails 7.1, not with Rails 6.1 or 7.0.

**Comment by dentarg** [comment]
Looks like the issue is that `psych` can't be installed because there's no `libyaml`: https://github.com/lwe/page_title_helper/actions/runs/9157727571/job/25246440277?pr=186#step:6:155

It all checks out, https://github.com/actions/runner-images/blob/36549632cea38ed6a673524db463e2a030ccf247/images/ubuntu/Ubuntu2204-Readme.md has `libyaml-dev` but https://github.com/actions/runner-images/blob/36549632cea38ed6a673524db463e2a030ccf247/images/ubuntu/Ubuntu2404-Readme.md has no mention of libyaml.

And now I see that @eregon has already opened an issue about that 😄   https://github.com/actions/runner-images/issues/9895

**Comment by eregon** [comment]
Yep, and in any case errors during bundle install are never a bug in setup-ruby.
