### ISSUE TITLE
Are the rubies built with, or allow using, jemalloc?

### ISSUE THREAD

**Issue by hms** [ruby/setup-ruby#610]
First, thank you for this wonderful time saver!

Are the current builds using jemalloc?  Or if not, is there a way to optional args my way into jemalloc?  

I'm struggling with OOM issues with a very action build and test config and noticed that my local environment that is built with jemallc use ½ to ⅓ the memory during testing and was hoping there was an easy way to explore if that might solve the problems (at least for now).

Thanks in advance.

**Comment by eregon** [comment]
That's not available and it would be too much work to add and double the number of builds.
The alternative to have only jemalloc builds is also problematic because it's a non-default and probably less stable config.

Maybe https://bugs.ruby-lang.org/issues/15667 can help (e.g. using 3.3 or setting MALLOC_ARENA_MAX).
