### ISSUE TITLE
Add jruby-9.4.8.0 to @v1

### ISSUE THREAD

**Issue by jimtng** [ruby/setup-ruby#618]
Thanks for adding jruby-9.4.8.0 support! We are looking forward to having it on the @v1 branch to use it in our actions. Thanks!

**Comment by eregon** [comment]
Thanks for the report, there is already [a release with it](https://github.com/ruby/setup-ruby/releases/tag/v1.184.0) but https://github.com/ruby/setup-ruby/tree/v1 points to https://github.com/ruby/setup-ruby/releases/tag/v1.181.0.
Somehow the workflow bumping the v1 branch to the latest release didn't run since I automated releases, I guess because of this rule of GitHub Actions not triggering other GitHub Actions.
