### ISSUE TITLE
ruby-dev-builder - macOS head - use OpenSSL 3 ?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#631]
ruby/ruby currently builds macOS head with OpenSSL 3, see [.github/actions/setup/macos/action.yml](https://github.com/ruby/ruby/blob/master/.github/actions/setup/macos/action.yml)

There's some variance, but the macOS builds of Ruby 3.1 thru 3.3 all use OpenSSL 3.  See [MSP-Greg/github-actions-ruby-info latest CI](https://github.com/MSP-Greg/github-actions-ruby-info/actions/runs/10191201765)

Currently, ruby-dev-builder is using OpenSSL 1.1.1w for macOS head builds.

Note - Issues are shutoff in ruby-dev-builder.  Also, the GHA macOS images do not have OpenSSL 3 installed.  See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md, it shows only 'OpenSSL 1.1.1w 11 Sep 2023'.  Not sure how the macOS release builds deal with that...

**Comment by eregon** [comment]
Yeah if openssl@3 is not installed (on some macOS runners) then we shouldn't use that, otherwise it'll fail at runtime or we'll have to pay the cost to `brew install openssl@3` every time which is a big no-no.

The philosophy here is "use what is installed on the machines, and let the CRuby configure script pick what it picks by default".

**Comment by eregon** [comment]
Mmh, it seems openssl@3 *is* installed on macos-14 from your logs:
https://github.com/MSP-Greg/github-actions-ruby-info/actions/runs/10191201765/job/28192124078#step:4:58

The behavior is basically "whatever `ruby-build` + CRuby do", at the time it was built.
Since I don't see any concrete issue/problem here, I don't see any reason to change anything and to not keep things simple as-they-are.

**Comment by MSP-Greg** [comment]
@eregon

Thanks.  The repo [MSP-Greg/github-actions-ruby-info](https://github.com/MSP-Greg/github-actions-ruby-info/actions) is all about Ruby versions.

I've got another repo ([MSP-Greg/actions-image-testing](https://github.com/MSP-Greg/actions-image-testing/actions)), which is info about the runner images.  I just added 'brew list --versions' to the macOS workflow.

All three macOS images have OpenSSL 3 installed, see:

[macos-12](https://github.com/MSP-Greg/actions-image-testing/actions/runs/10307093647/job/28531625226#step:7:139)
[macos-13](https://github.com/MSP-Greg/actions-image-testing/actions/runs/10307093647/job/28531625018#step:7:105)
[macos-14](https://github.com/MSP-Greg/actions-image-testing/actions/runs/10307093647/job/28531624788#step:7:85)

I guess the ReadMe file I linked to needs an update.

Anyway, will you accept a PR for this in ruby-dev-builder?  I think it's probably just two line changes.

**Comment by MSP-Greg** [comment]
@eregon

See https://github.com/ruby/ruby-dev-builder/pull/12

It was a one line change...
