### ISSUE TITLE
Error: Unknown version 3.4.1 for ruby on ubuntu-22.04

### ISSUE THREAD

**Issue by Ahmedhossamdev** [ruby/setup-ruby#678]
error: Error: Unknown version 3.4.1 for ruby on ubuntu-22.04
        Available versions for ruby on ubuntu-22.04
        
3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.3.0-preview1, 3.3.0-preview2, 3.3.0-preview3, 3.3.0-rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.4.0-preview1, 3.4.0-preview2, 3.4.0-rc1, head, debug, asan

Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1

**Comment by pruzicka** [comment]
I guess it takes some small amounts of time :)

**Comment by Ahmedhossamdev** [comment]
@pruzicka Yeah I think

**Comment by ashmaroli** [comment]
Yes. A delay is expected given the festive season but also since the logistics are handled manually by different maintainers in different repositories.
Additionally, this action also depends on pre-built rubies which is maintained at https://github.com/ruby/ruby-builder which at the time of this comment is only at **Ruby 3.4.0**. So, that's an additional layer of delay.

**Comment by Ahmedhossamdev** [comment]
Yeah, thanks for clarifying this. @ashmaroli

**Comment by eregon** [comment]
Done: https://github.com/ruby/setup-ruby/releases/tag/v1.206.0

**Comment by Ahmedhossamdev** [comment]
@eregon 🔥🔥
