### ISSUE TITLE
ruby-dev-builder - head builds failing

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#69]
I noticed that head builds were stuck back 16-June, and had a look at ruby-dev-builder.  Issues aren't enabled there, so I posted here.

I made a few changes, and things seem to be passing.  See the following, which I ran in my fork:

https://github.com/MSP-Greg/ruby-dev-builder/commit/3fdb427033

The builds are here:
https://github.com/MSP-Greg/ruby-dev-builder/releases/tag/master

I don't know if you can try one locally, not sure if my changes affected the saved builds...

**Comment by eregon** [comment]
Good catch.

I need a better way to get notifications for failures in the `-dev-builder` repos.
I don't want to "Watch" them because it would create so many emails about nightly releases.
That's also the reason I don't have issues there, so they are filed here and of course I watch this repo.

Does `make prepare-gems` fixes it then?
It shouldn't be needed for `make test-all`.
Maybe I should run `test-all` before any other testing, in the case other testing somehow affects whether `test-all` passes.

**Comment by eregon** [comment]
Just running `test-all` before the rest seems to work:
https://github.com/ruby/ruby-dev-builder/commit/ae62ac36631e5c53ac8971f9f7c09d84b9a0ce37
https://github.com/ruby/ruby-dev-builder/runs/861028580?check_suite_focus=true

**Comment by MSP-Greg** [comment]
> Does make prepare-gems fixes it then?

Please keep in mind that ruby-loco has been very stable for quite a while, so building is something I often have to review/catch up on.  I don't know if it affects CI or it affects install.  I may not be needed, or it may just be needed when building from the repo, as opposed to building with a tarball...

I think some of the issues may be related to the Gemfile?

> Maybe I should run test-all before any other testing

I would hope the two would be independent, or not affect each other.

> I don't want to "Watch" them because it would create so many emails about nightly releases.

With ruby-loco's Actions builds, I'm not creating new releases, so the only notifications I get are failures.  Maybe you can adjust the notifications?

I'll get that PR revised for MSYS2 bash here, I've been looking at Puma/nio4r/JRuby and getting frustrated.

**Comment by MSP-Greg** [comment]
> Just running test-all before the rest seems to work:

'the rest' being the `bundle install` step, etc.  Ok by me.

**Comment by eregon** [comment]
Since ruby/ruby@459670d47f8528db8f5d4f28aeac191b1af66d81, prepare-gems/update-gems/extract-gems when building from the repo, so that seems fine.

> I think some of the issues may be related to the Gemfile?

Yeah, that sounds likely.

> I would hope the two would be independent, or not affect each other.

Apparently not.

> With ruby-loco's Actions builds, I'm not creating new releases, so the only notifications I get are failures. Maybe you can adjust the notifications?

Actually I noticed I got the emails, they get automatically classified in a folder I don't look often (because there are way too many emails getting there, i.e., multiple emails for every PR I make).

> I'll get that PR revised for MSYS2 bash here, I've been looking at Puma/nio4r/JRuby and getting frustrated.

Thanks!
