### ISSUE TITLE
ruby/setup-ruby@v1 does not run in a self-hosted runner

### ISSUE THREAD

**Issue by navarroaxel** [ruby/setup-ruby#88]
I can't run `ruby/setup-ruby@v1` in a self-hosted runner. My action works fine in GitHub-hosted runner `ubuntu-latest` but I tried with my own docker image, the `myoung34/github-runner:ubuntu-focal` image and `tcardonne/github-runner:ubuntu-20.04` and `VM with Ubuntu 20.04`. I always get the same error:

I tried ruby 2.6 and 2.7, looks like node can't spawn the process. Maybe a missing dependency in the runner?

```bash
##[error]There was an error when attempting to execute the process '/root/.rubies/ruby-2.7.1/bin/gem'. This may indicate the process failed to start. Error: spawn /root/.rubies/ruby-2.7.1/bin/gem ENOENT
```

My simple repo to test this: https://github.com/navarroaxel/ruby-runner/runs/1133643210

My workflow:
```
name: Ruby
on: push
jobs:
  publish:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.45.0
      with:
        ruby-version: 2.7
```
output:
```bash
 Run ruby/setup-ruby@v1
  Took   0.00 seconds
Run ruby/setup-ruby@v1
  with:
    ruby-version: 2.7
    bundler: default
    bundler-cache: false
    working-directory: .
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/enable-shared/ruby-2.7.1-ubuntu-20.04.tar.gz
  Took  23.29 seconds
Extracting Ruby
  /usr/bin/tar -xz -C /root/.rubies -f /tmp/work/_temp/acd71600-4e4d-4beb-bca0-db920cc72d0c
  Took   0.34 seconds
Installing Bundler
  /root/.rubies/ruby-2.7.1/bin/gem install bundler -v ~> 2 --no-document
  Took   0.00 seconds
##[error]There was an error when attempting to execute the process '/root/.rubies/ruby-2.7.1/bin/gem'. This may indicate the process failed to start. Error: spawn /root/.rubies/ruby-2.7.1/bin/gem ENOENT
```

If I run the downloaded binaries in the VM I get this error:

```bash
$ ./.rubies/ruby-2.7.1/bin/gem 
-bash: ./../.rubies/ruby-2.7.1/bin/gem: /home/runner/.rubies/ruby-2.7.1/bin/ruby: bad interpreter: No such file or directory
$ ./.rubies/ruby-2.7.1/bin/ruby 
./.rubies/ruby-2.7.1/bin/ruby: error while loading shared libraries: libruby.so.2.7: cannot open shared object file: No such file or directory
```

**Comment by chrisyates-sage** [comment]
+1 for me, only I am using the Amazon Linux 2 image, and ruby/setup-ruby fails because the image is not Ubuntu. Whereas, actions/setup-ruby fails because ruby 2.6 isn't in the tool cache.  Could you extend support for Amazon Linux too, so we can run Ruby in spot instance runners?

**Comment by navarroaxel** [comment]
> +1 for me, only I am using the Amazon Linux 2 image, and ruby/setup-ruby fails because the image is not Ubuntu. Whereas, actions/setup-ruby fails because ruby 2.6 isn't in the tool cache. Could you extend support for Amazon Linux too, so we can run Ruby in spot instance runners?

This is not the same issue because the binaries for `Amazon Linux 2` should be added to https://github.com/ruby/ruby-builder/releases or change this action to fallback to `Ruby Version Manager` if the OS is not `Ubuntu`.

**Comment by eregon** [comment]
The point of this action is to be fast.
To do that, we need to precompile Ruby.

The precompiled Rubies are specific to a given virtual environment so architecture, OS, libssl version and more.
I expect the precompiled CRubies work on no environment except those of GitHub-hosted runners:
https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
(JRuby and TruffleRuby releases OTOH are more portable across e.g. Linux distributions, but e.g. TruffleRuby would need to recompile against the system libssl which takes time)

Attempting to make precompiled CRuby more independent of the underlying environment seems extremely hard work and many attempts seem to have failed, so I will not do that.

So I think unfortunately this issue is not solvable, or at least it's not the responsibility of ruby/setup-ruby to solve it.
It would be good if we can detect such cases reliably and fail early.

If you want to run on a different virtual environment/runner, please either use a system Ruby or compile your own. We cannot possibly precompile Ruby for all possible Docker images, etc.

Maybe we can have a special `ruby-version: system/PATH` that uses whatever pre-installed `ruby` is in PATH, I'm not sure if that's useful.

Using RVM is not a good way either, it expects the shell process to stay alive to maintain state and that just doesn't work with GitHub Actions.

One last idea is there could be forks of `ruby/ruby-builder` that build precompiled Rubies on custom images/runners, and have a way to configure `ruby/setup-ruby` to use that. I'm not against that, but I would not maintain those forks, there is already more than enough work to precompile for all GitHub-hosted runners.

**Comment by eregon** [comment]
FWIW GitHub `ubuntu-*` environments are not just vanilla Ubuntu and IIRC the libssl version is different.
For the specific case in the first post, feel free to debug by running the commands printed by `setup-ruby` manually in Docker.

**Comment by navarroaxel** [comment]
Hey @LinuxBozo, could you please help me with this issue? I read your PR but I can't make this work.
Which is the minimum config to this? I'm using this Dockerfile https://github.com/navarroaxel/docker-github-runner/blob/docker/docker/Dockerfile

Thanks!

**Comment by eregon** [comment]
I tried to clarify the docs in https://github.com/ruby/setup-ruby/commit/153ca5e38fe769fe88e981c5f8d98c56c1ada733.
In other words, self-hosted might work in some cases, but there is no guarantee and it's inherently fragile.

**Comment by LinuxBozo** [comment]
@navarroaxel You aren't actually dropping privileges and running your process as the `runner` user as outlined in the docs, but are running as root. There's quite a few assumptions based around that in the github runner itself, and in fact, it should complain about running as root.

**Comment by navarroaxel** [comment]
@LinuxBozo the [docs](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#docker-container-filesystem) says `GitHub Actions must be run by the default Docker user (root).`

**Comment by LinuxBozo** [comment]
@navarroaxel That's right.. Docker based Actions must run as root. 

What it doesn't say is that the runner itself must be run as root. In fact, when using the default scripts to launch the runner, it has an explicit check to make sure you aren't running as root: https://github.com/actions/runner/blob/master/src/Misc/layoutroot/run.sh#L3

**Comment by eregon** [comment]
I'd like to close this issue.
It seems the original error is due to an incorrect setup of the GitHub Actions runner.
Docker-based Actions are unrelated, this is a so-called JavaScript-based Action so it works on other OS than Linux.

In short this action does not support self-hosted runners, because it's not possible to precompile Rubies for all variants of them.

**Comment by navarroaxel** [comment]
I only want a github runner (in an Ubuntu VM or an Ubuntu Docker image) which can run this tool.

I think my image is not the problem @eregon, because I can run super linter, node, android, java, fastlane actions, etc.

Anyway I have added `apt install ruby-dev` to the docker build.

**Comment by eregon** [comment]
Are the Docker images behind GitHub Actions available publicly? If so that would likely be the best way to ensure a similar environment.

I just saw you updated the description:
> If I run the downloaded binaries in the VM I get this error:
> 
> ```shell
> $ ./.rubies/ruby-2.7.1/bin/gem 
> -bash: ./../.rubies/ruby-2.7.1/bin/gem: /home/runner/.rubies/ruby-2.7.1/bin/ruby: bad interpreter: No such file or directory
> $ ./.rubies/ruby-2.7.1/bin/ruby 
> ./.rubies/ruby-2.7.1/bin/ruby: error while loading shared libraries: libruby.so.2.7: cannot open shared object file: No such file or directory
> ```

OK, so that means the `ruby` binary cannot find `libruby.so`, most likely because it's not installed at the same place.
What is you current working directory (`pwd`) when executing those commands?
And is `/home/runner` a real directory or a symlink (to which path)?

Assuming you downloaded https://github.com/ruby/ruby-builder/releases/download/enable-shared/ruby-2.7.1-ubuntu-20.04.tar.gz,
then (on my system):
```
$ ldd bin/ruby 
	linux-vdso.so.1 (0x00007ffde7bb3000)
	libruby.so.2.7 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007fe7a1cb1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe7a1ea7000)

$ readelf -d bin/ruby

Dynamic section at offset 0x2d78 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libruby.so.2.7]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/runner/.rubies/ruby-2.7.1/lib]
...
```
So it expects to find `libruby.so.2.7` in `/home/runner/.rubies/ruby-2.7.1/lib`, which means `/home/runner/.rubies/ruby-2.7.1/lib/libruby.so.2.7` must exist. Does it exist in your case?

**Comment by KengoTODA** [comment]
Note for other users:
In my case, this problem was caused because of wrong linux user name. [README.md explained](https://github.com/ruby/setup-ruby/blob/11082225e459fa3affba355ca510939dc9438b72/README.md#using-self-hosted-runners) that it should be `runner` but ours wasn't so. I could solve my problem by `sudo ln -s /home/theuser /home/runner`.

**Comment by emiltin** [comment]
If ruby/setup-ruby is not recommended on self-hosted runners (if architecture etc. is not guarateed to match GitHub runners), what would be the recommended way to install ruby? Is there another action?

**Comment by eregon** [comment]
It works on self-hosted runners and is documented as such.

**Comment by eregon** [comment]
As that doc says, either have your runners similar enough to GH-hosted runners and they can reuse the prebuilt Rubies, otherwise as said there as well you need to build Ruby in the toolcache (a standard GHA feature) and this action will use it.
