### ISSUE TITLE
Suggestion: new 'github-pages' value for 'ruby-version' 

### ISSUE THREAD

**Issue by maxim-belkin** [ruby/setup-ruby#96]
This is a request similar to actions/setup-ruby#86: it would've been great if we could specify Ruby version that is currently used by the GitHub's `github-pages` gem:
```
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'github-pages'
```
It can be extracted from https://pages.github.com/versions/ or https://pages.github.com/versions.json

**Comment by eregon** [comment]
Interesting that `ruby` is listed alongside gems on https://pages.github.com/versions/.

I am not sure if depending on an external URL like that is a good idea. It could be unreliable.
In general, this action makes no extra requests, except downloading Ruby itself.

If you are building your website using the github-pages gem, I think it's more reliable if you both fix the `github-pages` version (with a Gemfile.lock) and the ruby version.
Doesn't your github-pages project use a Gemfile.lock?

**Comment by maxim-belkin** [comment]
> I am not sure if depending on an external URL like that is a good idea.

I mean, we're on GitHub talking about a page on github.com :) so, it's not really "external"...

> If you are building your website using the github-pages gem, I think it's more reliable if you both fix the `github-pages` version (with a Gemfile.lock) and the ruby version.

Fixing both is a good idea. thanks!

> Doesn't your github-pages project use a Gemfile.lock?

We don't at the moment but we might if we fix the version of github-pages gem. Basically, the goal of our Gemfile is to test on a local machine that GitHub will be able to build a website. So, we want to have the latest version of the `github-pages` gem. But we can use some

**Comment by eregon** [comment]
> But we can use some

Non-terminated sentence?

How do you use this action then, if anyway the website is built by GitHub Pages' Jekyll?

If you want to build your website in a workflow using this action, then I believe it is recommended to use a fixed Ruby version and fixed version of `github-pages` or `jekyll` by having a `Gemfile.lock`, and then in a separate step just push the result to the `gh-pages` branch of your repository.

This seems a very specific use-case, and I think it can be achieved simply in your workflow using:
```
$ curl -s https://pages.github.com/versions.json | jq -r .ruby
2.7.1
```
and then composing that with https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable or https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter to pass it as the `ruby-version` input.

I'll close because I think it's easy to achieve separately and it seems too specific to be useful to many users, but feel free to continue the discussion.

**Comment by maxim-belkin** [comment]
> > But we can use some
> 
> Non-terminated sentence?

Yep. sorry about that :)


> then composing that with https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable or https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter to pass it as the `ruby-version` input.

👍 Yes, I'm aware of these. I just wanted to save some of my time :) Anyways, thank you!
